# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/syuchua/android_kernel_5.10_oneplus_mt6983
          kernel-dir: msm-5.10
          kernel-branch: oneplus/mt6983_t_13.0_oneplus_ace_2v
          config: defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          # ksu: true
          # ksu-version: main
          android-version: 14
          aosp-clang-version: r536225
          disable-lto: true
          anykernel3: true
